---

- name: Change vTM Config
  hosts: vtms
  tasks:
    - name: Change vserver
      virtual_server:
          name: test_vs
          password: "{{ admin_password }}"
          properties:
              basic:
                  port: 4321
    - name: Change pool
      pool:
          name: test_pool
          password: "{{ admin_password }}"
          properties:
              basic:
                  nodes_table:
                      - node: 10.0.0.10:80
                        weight: 1
                      - node: 10.0.0.11:80
                        weight: 1
